db_servers:
  children:
    db_servers_primary:
      hosts:
        pgsql1:
          ansible_host: 192.168.56.101
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/pgsql1/virtualbox/private_key
          repmgr_node_id: 1
    db_servers_replica:
      hosts:
        pgsql2:
          ansible_host: 192.168.56.102
          ansible_user: vagrant
          ansible_ssh_private_key_file: .vagrant/machines/pgsql2/virtualbox/private_key
          repmgr_node_id: 2

barman_servers:
  hosts:
    barman:
      primary_host: 192.168.56.101
      ansible_host: 192.168.56.20
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/barman/virtualbox/private_key

pgpool_servers:
  hosts:
    pgpool:
      ansible_host: 192.168.56.80
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/pgpool/virtualbox/private_key
  