---
- name: Apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Pgpool-II 
  apt:
    name: pgpool2
    state: present

- name: Setup Pgpool-II
  template:
    src: pgpool.conf.j2
    dest: /etc/pgpool2/pgpool.conf
  
- name: Start Pgpool-II
  service:
    name: pgpool2
    state: restarted
    enabled: yes
