---
- name: Install python3-psycopg2 using apt
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
    update_cache: yes
  become: true

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: true

- name: Copy postgresql.conf primary
  ansible.builtin.template:
    src: postgresql.conf.primary.j2
    dest: /etc/postgresql/14/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  become: yes

- name: Copy pg_hba.conf primary
  ansible.builtin.template:
    src: pg_hba.conf.primary.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644
  become: yes

- name: Ensure Primary PostgreSQL is running and enabled
  service:
    name: postgresql
    state: restarted
    enabled: true

- name: Create archive directory
  ansible.builtin.file:
    path: /var/lib/postgresql/archivedir/
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  become: yes



